// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// demographic_stochast
NumericVector demographic_stochast(NumericVector v, NumericMatrix tmat);
RcppExport SEXP ramasr_demographic_stochast(SEXP vSEXP, SEXP tmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tmat(tmatSEXP);
    __result = Rcpp::wrap(demographic_stochast(v, tmat));
    return __result;
END_RCPP
}
