# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demographic_stochast <- function(v, tmat) {
    .Call('dlmpr_demographic_stochast', PACKAGE = 'dlmpr', v, tmat)
}

#'environmental stochastic function in C++
#' @param tmat NumericMatrix. Vector with the initial abundance of each stage.
#' @param sdmat NumericMatrix. Transition matrix.
#' @param equalsign bool. Should the environmental deviations have all the same sign and magnitude? TRUE or FALSE
#' @export
envir_stochast <- function(tmat, sdmat, equalsign = TRUE) {
    .Call('dlmpr_envir_stochast', PACKAGE = 'dlmpr', tmat, sdmat, equalsign)
}

#' Single time step demographic projection function in C++
#' 
#' @param v0 NumericVector. Vector with the initial abundance of each stage.
#' @param tmat NumericMatrix. Transition matrix.
#' @param matsd NumericMatrix. Matrix with the standard deviation of the probabilities in tmat. 
#' @param stmat NumericMatrix. Matrix indicating for each transition probability in mat which part (i.e. which proportion) should be considered resulting from fecundity.
#' @param estamb bool. Environmental stochasticity included in population dynamics?
#' @param estdem bool. Demographic stochasticity included in population dynamics?
#' @param equalsign bool. Should the environmental deviations have all the same sign and magnitude?
#' @param tmat_fecundity bool. Should the first row of tmat as fecundities? TRUE or FALSE
#' @export
demo_proj <- function(v0, tmat, matsd = NULL, stmat = NULL, estamb = FALSE, estdem = FALSE, equalsign = TRUE, tmat_fecundity = FALSE) {
    .Call('dlmpr_demo_proj', PACKAGE = 'dlmpr', v0, tmat, matsd, stmat, estamb, estdem, equalsign, tmat_fecundity)
}

#' Multiple time step and repetition demographic projection function in C++
#' 
#' @param vn List. List of vectors for simulation.
#' @param tmat NumericMatrix. Transition matrix.
#' @param matsd NumericMatrix. Transtion matrix error.
#' @param stmat NumericMatrix. Matrix indicating for each transition probability in mat which part (i.e. which proportion) should be considered resulting from fecundity
#' @param estamb bool. Environmental stochasticity included in population dynamics?
#' @param estdem bool. Demographic stochasticity included in population dynamics?
#' @param equalsign Logical. Should the environmental deviations have all the same sign and magnitude?
#' @param tmat_fecundity bool Should the first row of tmat as fecundities? TRUE or FALSE
#' @param nrep int number of simulations
#' @param time int number of time-steps.
#' @export
demo_proj_n_cpp <- function(vn, tmat, matsd = NULL, stmat = NULL, estamb = FALSE, estdem = FALSE, equalsign = TRUE, tmat_fecundity = FALSE, nrep = 1L, time = 10L) {
    .Call('dlmpr_demo_proj_n_cpp', PACKAGE = 'dlmpr', vn, tmat, matsd, stmat, estamb, estdem, equalsign, tmat_fecundity, nrep, time)
}

meta_dispersal_fun <- function(dist, alpha, beta = 1, hanski_dispersal_kernal = TRUE) {
    .Call('dlmpr_meta_dispersal_fun', PACKAGE = 'dlmpr', dist, alpha, beta, hanski_dispersal_kernal)
}

#'C++ metapopulation function for a single timestep.
#' @param presence NumericVector Initial occupancy of each patch
#' @param dist_mat Exponential decay rate of patch connectivity (dispersion parameter)
#' @param Ei patch extinction rate at time i. note: In the future I need to pull this from demographic model.
#' @param y incidence function parameters.
#' @export
metapop <- function(presence, dist_mat, Ei, y) {
    .Call('dlmpr_metapop', PACKAGE = 'dlmpr', presence, dist_mat, Ei, y)
}

#'Simulate a metapopulation system in C++
#'this function is not complete.
#' @param time Number of time steps
#' @param dist Distances between patches (symetrical matrix)
#' @param area Area of patches - This needs to be calculated somehow - using occupancy models?
#' @param presence Initial occupancies of patches. Must be presence 1 or absence 0.
#' @param y incidence function parameters
#' @param x incidence function parameters
#' @param e Minimum area of patches
#' @param alpha Exponential decay rate of patch connectivity (dispersion parameter)
#' @param beta double parameter that represents the shape of the dispersal kernel.
#' @param hanski_dispersal_kernal bool if true uses hanski(1994), if false uses shaw(1995).
#' @param locations NULL or NumericMatrix Longitudes and latitudes of coordinates of the patches
#' @export
metapop_n <- function(time, dist, area, presence, y = 1, x = 1, e = 1, alpha = 1, beta = 1, hanski_dispersal_kernal = TRUE, locations = NULL) {
    .Call('dlmpr_metapop_n', PACKAGE = 'dlmpr', time, dist, area, presence, y, x, e, alpha, beta, hanski_dispersal_kernal, locations)
}

#'Simulate a metapopulation system in C++
#'this function is not complete.
#' @param nrep Number of simulations.
#' @param time Number of time steps
#' @param dist Distances between patches (symetrical matrix)
#' @param area Area of patches - This needs to be calculated somehow - using occupancy models?
#' @param presence Initial occupancies of patches. Must be presence 1 or absence 0.
#' @param y incidence function parameters
#' @param x incidence function parameters
#' @param e Minimum area of patches
#' @param alpha Exponential decay rate of patch connectivity (dispersion parameter)
#' @param beta double parameter that represents the shape of the dispersal kernel.
#' @param hanski_dispersal_kernal bool if true uses hanski(1994), if false uses shaw(1995).
#' @param locations NULL or NumericMatrix Longitudes and latitudes of coordinates of the patches
#' @export
metapop_n_cpp <- function(nrep, time, dist, area, presence, y = 1, x = 1, e = 1, alpha = 1, beta = 1, hanski_dispersal_kernal = TRUE, locations = NULL) {
    .Call('dlmpr_metapop_n_cpp', PACKAGE = 'dlmpr', nrep, time, dist, area, presence, y, x, e, alpha, beta, hanski_dispersal_kernal, locations)
}

