# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demographic_stochast <- function(v, tmat) {
    .Call('dlmpr_demographic_stochast', PACKAGE = 'dlmpr', v, tmat)
}

#'environmental stochastic function in C++
#' @param tmat NumericMatrix. Vector with the initial abundance of each stage.
#' @param sdmat NumericMatrix. Transition matrix.
#' @param equalsign bool. Should the environmental deviations have all the same sign and magnitude? TRUE or FALSE
#' @export
envir_stochast <- function(tmat, sdmat, equalsign = TRUE) {
    .Call('dlmpr_envir_stochast', PACKAGE = 'dlmpr', tmat, sdmat, equalsign)
}

#' Single time step demographic projection function in C++
#' 
#' @param v0 NumericVector. Vector with the initial abundance of each stage.
#' @param tmat NumericMatrix. Transition matrix.
#' @param matsd NumericMatrix. Matrix with the standard deviation of the probabilities in tmat. 
#' @param stmat NumericMatrix. Matrix indicating for each transition probability in mat which part (i.e. which proportion) should be considered resulting from fecundity.
#' @param estamb bool. Environmental stochasticity included in population dynamics?
#' @param estdem bool. Demographic stochasticity included in population dynamics?
#' @param equalsign bool. Should the environmental deviations have all the same sign and magnitude?
#' @param tmat_fecundity bool. Should the first row of tmat as fecundities? TRUE or FALSE
#' @export
demo_proj <- function(v0, tmat, matsd = NULL, stmat = NULL, estamb = FALSE, estdem = FALSE, equalsign = TRUE, tmat_fecundity = FALSE) {
    .Call('dlmpr_demo_proj', PACKAGE = 'dlmpr', v0, tmat, matsd, stmat, estamb, estdem, equalsign, tmat_fecundity)
}

#' Multiple time step and repetition demographic projection function in C++
#' 
#' @param vn List. List of vectors for simulation.
#' @param tmat NumericMatrix. Transition matrix.
#' @param matsd NumericMatrix. Transtion matrix error.
#' @param stmat NumericMatrix. Matrix indicating for each transition probability in mat which part (i.e. which proportion) should be considered resulting from fecundity
#' @param estamb bool. Environmental stochasticity included in population dynamics?
#' @param estdem bool. Demographic stochasticity included in population dynamics?
#' @param equalsign Logical. Should the environmental deviations have all the same sign and magnitude?
#' @param tmat_fecundity bool Should the first row of tmat as fecundities? TRUE or FALSE
#' @param nrep int number of simulations
#' @param time int number of time-steps.
#' @export
demo_proj_n_cpp <- function(vn, tmat, matsd = NULL, stmat = NULL, estamb = FALSE, estdem = FALSE, equalsign = TRUE, tmat_fecundity = FALSE, nrep = 1L, time = 10L) {
    .Call('dlmpr_demo_proj_n_cpp', PACKAGE = 'dlmpr', vn, tmat, matsd, stmat, estamb, estdem, equalsign, tmat_fecundity, nrep, time)
}

